-   repo: git@github.com:pre-commit/pre-commit-hooks.git
    sha: v0.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E265,E309,E501
        # E265 deals with spacing inside of comments - breaks human formatting
        # E309 puts a blank line after class declarations - doesn't work well with docstrings
        # E501 reformats lines to fit in --max-line-length poorly
    -   id: check-yaml
    -   id: debug-statements
        language_version: python2.7
    -   id: flake8
        language_version: python2.7
        exclude: docs/conf.py.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,docs,virtualenv_run,setup.py,yelpsoa-configs
        filename: (.+).py,(.+).wsgi
        max-line-length: 80
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: name-tests-test
        exclude: (tests/helpers/(.+).py|tests/models/testing_db.py|tests/views/api_test_base.py)
    -   id: fix-encoding-pragma
    -   id: check-added-large-files
    -   id: check-byte-order-marker
-   repo: git@github.com:asottile/reorder_python_imports.git
    sha: v0.3.0
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
        args:
        - --add-import
        - from __future__ import absolute_import
        - --add-import
        - from __future__ import unicode_literals
