branches:
  only:
  - master
  - /^v[0-9.]+$/
language: python
python:
- '2.7'
services:
  - docker
install:
 - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
 - wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
 - sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
 - sudo apt-get update -q
 - sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server
 - sudo mysql_upgrade
 - pip install coveralls tox
script: 
  - make -f Makefile-opensource test
  - make -f Makefile-opensource itest
after_success:
  - coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker-compose  --file=docker-compose-opensource.yml build

    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

    docker tag schematizer_schematizerservice:latest yelp/schematizer_service:latest;
    docker tag schematizer_schematizerconfigs:latest yelp/schematizer_schematizerconfigs:latest;
    docker tag schematizer_schematizerdatabase:latest yelp/schematizer_schematizerdatabase:latest;

    docker push docker.io/yelp/schematizer_service;
    docker push docker.io/yelp/schematizer_schematizerconfigs;
    docker push docker.io/yelp/schematizer_schematizerdatabase;
    fi
