schematizerdatabase:
    build: schema/

schematizerconfigs:
    build: acceptance/configs/

schematizerservice:
    build: .
    links:
        - schematizerdatabase
    volumes_from:
        - schematizerconfigs
    ports:
        - "49257:8888"

schematizerserviceopensource:
    build: .
    links:
        - schematizerdatabase
    volumes_from:
        - schematizerconfigs
    ports:
        - "49257:8888"
    environment:
      - SERVICE_ENV_CONFIG_PATH=config-env-open-source.yaml
